# Generated by Django 5.2.8 on 2025-11-17 11:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Car name (e.g., 'Mazda MX-5 Cup')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "car_class",
                    models.CharField(
                        blank=True,
                        help_text="Car class (e.g., 'Sports Car')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice"),
                            ("qualifying", "Qualifying"),
                            ("race", "Race"),
                            ("time_trial", "Time Trial"),
                            ("testing", "Testing"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                (
                    "session_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the session occurred",
                    ),
                ),
                (
                    "ibt_file",
                    models.FileField(
                        help_text="Uploaded IBT telemetry file",
                        upload_to="telemetry/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["ibt", "IBT"]
                            )
                        ],
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "air_temp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Air temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "track_temp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Track temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weather_type",
                    models.CharField(
                        blank=True, help_text="Weather condition", max_length=50
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow public viewing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="telemetry.car",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lap_number",
                    models.IntegerField(help_text="Lap number in the session"),
                ),
                (
                    "lap_time",
                    models.DecimalField(
                        decimal_places=4, help_text="Lap time in seconds", max_digits=10
                    ),
                ),
                (
                    "sector1_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sector 1 time",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sector2_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sector 2 time",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sector3_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sector 3 time",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="Whether lap is clean (no off-tracks)"
                    ),
                ),
                (
                    "is_personal_best",
                    models.BooleanField(
                        default=False,
                        help_text="Personal best lap for this track/car combo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laps",
                        to="telemetry.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "lap_number"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow public viewing of team telemetry",
                    ),
                ),
                (
                    "allow_join_requests",
                    models.BooleanField(
                        default=True, help_text="Allow users to request to join"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="telemetry.team",
            ),
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iracing_id",
                    models.CharField(
                        blank=True,
                        help_text="iRacing Member ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for leaderboards",
                        max_length=100,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_members",
                        to="telemetry.team",
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="telemetry.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["team", "-joined_at"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="telemetry.TeamMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Telemetry data arrays indexed by channel name"
                    ),
                ),
                (
                    "sample_count",
                    models.IntegerField(help_text="Number of samples in this lap"),
                ),
                (
                    "max_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum speed in km/h",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "avg_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average speed in km/h",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lap",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="telemetry.lap",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry data",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Track name (e.g., 'Road Atlanta')", max_length=200
                    ),
                ),
                (
                    "configuration",
                    models.CharField(
                        blank=True,
                        help_text="Configuration (e.g., 'Full Course')",
                        max_length=100,
                    ),
                ),
                (
                    "length_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Track length in kilometers",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "turn_count",
                    models.IntegerField(
                        blank=True, help_text="Number of turns", null=True
                    ),
                ),
                (
                    "gps_lat_min",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lat_max",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng_min",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gps_lng_max",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "configuration"],
                "unique_together": {("name", "configuration")},
            },
        ),
        migrations.AddField(
            model_name="session",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="telemetry.track",
            ),
        ),
        migrations.AddIndex(
            model_name="lap",
            index=models.Index(
                fields=["session", "lap_time"], name="telemetry_l_session_bec70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lap",
            index=models.Index(
                fields=["is_valid", "lap_time"], name="telemetry_l_is_vali_dc97b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lap",
            unique_together={("session", "lap_number")},
        ),
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together={("team", "user")},
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["driver", "track", "car"], name="telemetry_s_driver__d22b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["processing_status"], name="telemetry_s_process_6b8353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["-session_date"], name="telemetry_s_session_c2dd28_idx"
            ),
        ),
    ]
