# Generated by Django 5.2.8 on 2025-11-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_alter_session_car_alter_session_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_class",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Car class (e.g., 'Sports Car')",
                max_length=100,
            ),
        ),
    ]
