# Generated by Django 5.2.8 on 2025-11-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0003_alter_car_car_class"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Analysis name (e.g. 'Baseline vs New Setup')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional notes about this analysis"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow public viewing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        help_text="Car these laps are from (optional, for filtering)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telemetry.car",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laps to compare in this analysis",
                        related_name="analyses",
                        to="telemetry.lap",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: share with team",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="telemetry.team",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Track these laps are from (optional, for filtering)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="telemetry.track",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analyses",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["driver", "-updated_at"],
                        name="telemetry_a_driver__f73a02_idx",
                    )
                ],
            },
        ),
    ]
