# Generated by Django 5.2.8 on 2025-11-17 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0004_analysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_version",
                    models.CharField(help_text="Version before update", max_length=50),
                ),
                (
                    "new_version",
                    models.CharField(
                        blank=True, help_text="Version after update", max_length=50
                    ),
                ),
                (
                    "old_commit",
                    models.CharField(
                        blank=True, help_text="Git commit before update", max_length=50
                    ),
                ),
                (
                    "new_commit",
                    models.CharField(
                        blank=True, help_text="Git commit after update", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.TextField(
                        blank=True, help_text="Current status or error message"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Update progress percentage (0-100)"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "log_file",
                    models.TextField(blank=True, help_text="Path to update log file"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="telemetry_s_created_475972_idx"
                    ),
                    models.Index(
                        fields=["status"], name="telemetry_s_status_6a7686_idx"
                    ),
                ],
            },
        ),
    ]
