# Generated by Django 5.2.8 on 2025-11-17 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0005_systemupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="ibt_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded IBT telemetry file",
                null=True,
                upload_to="telemetry/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(["ibt", "IBT"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("practice", "Practice"),
                    ("qualifying", "Qualifying"),
                    ("race", "Race"),
                    ("time_trial", "Time Trial"),
                    ("testing", "Testing"),
                    ("imported", "Imported Lap"),
                ],
                default="practice",
                max_length=20,
            ),
        ),
    ]
