# Generated by Django 5.2.8 on 2025-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0006_alter_session_ibt_file_alter_session_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="discord_webhook_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord webhook URL for sharing laps to team channel",
                max_length=500,
            ),
        ),
    ]
