# Generated by Django 5.2.8 on 2025-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0007_team_discord_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="driver_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Driver name from iRacing (not username)",
                max_length=100,
            ),
        ),
    ]
