# Generated by Django 5.2.8 on 2025-11-18 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0008_session_driver_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="connection_state",
            field=models.CharField(
                choices=[
                    ("disconnected", "Disconnected"),
                    ("connected", "Connected"),
                    ("error", "Error"),
                ],
                default="disconnected",
                help_text="Live connection state",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="is_live",
            field=models.BooleanField(
                default=False, help_text="Currently streaming live telemetry"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="last_telemetry_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last received telemetry data",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["is_live", "-last_telemetry_update"],
                name="telemetry_s_is_live_c04be4_idx",
            ),
        ),
    ]
