# Generated by Django 5.2.8 on 2025-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0009_session_connection_state_session_is_live_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="api_token",
            field=models.CharField(
                blank=True,
                help_text="API token for telemetry client authentication",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
