# Generated by Django 5.2.8 on 2025-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0010_add_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="enable_pb_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Enable Discord notifications when you set a personal best",
            ),
        ),
    ]
