# Generated by Django 5.2.8 on 2025-11-19 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0011_driver_enable_pb_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["car_class"], name="telemetry_c_car_cla_e42287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["iracing_id"], name="telemetry_d_iracing_dd7b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lap",
            index=models.Index(
                fields=["is_personal_best"], name="telemetry_l_is_pers_f53919_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lap",
            index=models.Index(
                fields=["is_valid", "is_personal_best", "lap_time"],
                name="telemetry_l_is_vali_79a384_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["is_public"], name="telemetry_t_is_publ_59c849_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["owner"], name="telemetry_t_owner_i_e763cc_idx"),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["user", "role"], name="telemetry_t_user_id_b96133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "role"], name="telemetry_t_team_id_6b9142_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["name"], name="telemetry_t_name_fe9f4b_idx"),
        ),
    ]
