# Generated by Django 5.2.8 on 2025-11-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0012_car_telemetry_c_car_cla_e42287_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to car image/silhouette",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="background_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to track background image",
                max_length=500,
            ),
        ),
    ]
