# Generated by Django 5.2.8 on 2025-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0013_car_image_url_track_background_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to car image/silhouette",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="background_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to track background image",
                max_length=500,
                null=True,
            ),
        ),
    ]
