# Generated by Django 5.2.8 on 2025-11-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0014_allow_null_image_urls"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analysis",
        ),
    ]
