# Generated by Django 5.2.8 on 2025-11-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0015_remove_analysis_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemUpdate",
        ),
    ]
