# Generated by Django 5.2.8 on 2025-11-24 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0016_remove_systemupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA256 hash of uploaded IBT file for duplicate detection",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["driver", "file_hash"], name="telemetry_s_driver__eedd1a_idx"
            ),
        ),
    ]
