# Generated by Django 5.2.8 on 2025-11-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0017_session_file_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="setup_name",
            field=models.CharField(
                blank=True,
                help_text="Setup filename used during this session",
                max_length=255,
            ),
        ),
    ]
