# Generated by Django 5.2.8 on 2025-11-24 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0018_session_setup_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from user explaining why they want to join",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of invited user", max_length=254
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from the inviter"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Invitation expires after 7 days"),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="is_default_team",
            field=models.BooleanField(
                default=False, help_text="Default team for new users (only one allowed)"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["is_default_team"], name="telemetry_t_is_defa_cb5b88_idx"
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="telemetry.team",
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_team_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User object if they exist in the system",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="telemetry.team",
            ),
        ),
        migrations.AddIndex(
            model_name="joinrequest",
            index=models.Index(
                fields=["team", "status"], name="telemetry_j_team_id_7334dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joinrequest",
            index=models.Index(
                fields=["user", "status"], name="telemetry_j_user_id_c3df23_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="joinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("team", "user"),
                name="unique_pending_join_request",
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["team", "status"], name="telemetry_t_team_id_89f712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["email", "status"], name="telemetry_t_email_335366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(fields=["token"], name="telemetry_t_token_cd6cc5_idx"),
        ),
    ]
