"""
Django settings for garage project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application version
VERSION_FILE = BASE_DIR.parent / 'VERSION'
try:
    with open(VERSION_FILE, 'r') as f:
        VERSION = f.read().strip()
except FileNotFoundError:
    VERSION = '1.0.0'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in environment variables - no insecure default
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG defaults to False for security - must explicitly enable for development
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# CSRF Trusted Origins (for non-standard ports and reverse proxies)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:42069,http://127.0.0.1:42069',
    cast=lambda v: [s.strip() for s in v.split(',')]
)


# Application definition

INSTALLED_APPS = [
    # Daphne MUST be first for ASGI support
    'daphne',

    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'channels',
    'django_celery_results',  # Optional: store Celery results in database
    # Note: We use Leaflet.js directly in templates, not django-leaflet (requires GDAL)

    # Local apps
    'telemetry',
]

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'garage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # For media file URLs
                'django.template.context_processors.static',  # For static file URLs
            ],
        },
    },
]

WSGI_APPLICATION = 'garage.wsgi.application'

# ASGI Application (for WebSocket support via Django Channels)
ASGI_APPLICATION = 'garage.asgi.application'

# Channel Layers Configuration (Redis backend for WebSockets)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('REDIS_URL', default='redis://localhost:6379/0')],
            "capacity": 1500,  # Maximum messages in queue
            "expiry": 10,      # Message expiry time in seconds
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL with psycopg3 and native connection pooling
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='ridgway_garage'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'CONN_MAX_AGE': 0,  # MUST be 0 when using connection pooling
        'OPTIONS': {
            'pool': {
                'min_size': 2,      # Minimum connections in pool
                'max_size': 10,     # Maximum connections in pool
                'timeout': 10,      # Connection timeout in seconds
            },
        },
    }
}

# Celery Configuration
# https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Email Configuration
# Gmail SMTP settings (or use console backend for development)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')  # Gmail address
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')  # Gmail App Password
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')
SERVER_EMAIL = config('SERVER_EMAIL', default='')

# Password reset token expiry (in seconds) - default 24 hours
PASSWORD_RESET_TIMEOUT = config('PASSWORD_RESET_TIMEOUT', default=86400, cast=int)

# Login/logout redirects
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Root static folder for Tailwind CSS output
]

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File Storage Configuration (Django 4.2+ format)
# Uses local filesystem with easy migration path to S3
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    # S3 Storage (future)
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': config('AWS_STORAGE_BUCKET_NAME'),
                'access_key': config('AWS_ACCESS_KEY_ID'),
                'secret_key': config('AWS_SECRET_ACCESS_KEY'),
                'region_name': config('AWS_S3_REGION_NAME', default='us-east-1'),
                'default_acl': 'private',
                'file_overwrite': False,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    # Local Filesystem Storage
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': MEDIA_ROOT,
                'base_url': MEDIA_URL,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# File Upload Settings
# IBT files can exceed 1GB for long sessions (e.g., Nurburgring endurance)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB - files larger than this use temp file
DATA_UPLOAD_MAX_MEMORY_SIZE = 2147483648  # 2GB max request size
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Maximum upload size (2GB for large telemetry files)
MAX_UPLOAD_SIZE = 2147483648  # 2GB in bytes

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Headers Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#security

# Browser XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# HTTP Strict Transport Security (HSTS)
# Forces browsers to use HTTPS - only enable in production with SSL
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Disable SSL redirect if nginx handles SSL termination (default: False to avoid redirect loops)
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# Session Security
SESSION_COOKIE_AGE = 5184000  # 60 days
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on activity (resets the 60-day timer)
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# CSRF Cookie Security
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access
CSRF_COOKIE_SAMESITE = 'Lax'

# Content Security Policy (CSP)
# Note: Using 'unsafe-inline' for now due to Bootstrap/Plotly inline scripts
# TODO: Migrate to nonce-based CSP when refactoring frontend
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",  # Required for Bootstrap and Plotly
    "https://cdn.jsdelivr.net",  # CDN for Bootstrap/Leaflet
    "https://cdn.plot.ly",  # Plotly.js
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",  # Required for Bootstrap
    "https://cdn.jsdelivr.net",
)
CSP_IMG_SRC = (
    "'self'",
    "data:",  # For inline images in charts
    "https://*.openstreetmap.org",  # OSM tiles for Leaflet
    "https://*.tile.openstreetmap.org",
)
CSP_FONT_SRC = (
    "'self'",
    "data:",
    "https://cdn.jsdelivr.net",
)
CSP_CONNECT_SRC = (
    "'self'",
    "ws://localhost:8000" if DEBUG else "",  # WebSocket in development
    "wss://*" if not DEBUG else "",  # WebSocket in production
)
